# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    #- name: Test
    #  run: dotnet test --no-build --verbosity normal

    - name: Set Version
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        PACKAGE_VERSION=1.1.${GITHUB_RUN_NUMBER}
        echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
        echo "Package Version: $PACKAGE_VERSION"

    - name: Package
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: dotnet pack --no-build --configuration Release /p:Version=${PACKAGE_VERSION} -o packages

    - name: Push to NuGet
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: dotnet nuget push "packages/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

    - name: Tag Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git tag -a v${PACKAGE_VERSION} -m "Release v${PACKAGE_VERSION}"
        git push origin v${PACKAGE_VERSION}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#    - name: Publish Nuget to GitHub registry
#      run: dotnet nuget push ./src/bin/Release/*.nupkg -s https://nuget.pkg.github.com/FlatlinerDOA/index.json -k ${GITHUB_TOKEN}
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
